#!/usr/bin/env bash -ex

RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Set up the build user and sudo access
echo -e "${YELLOW}==>${WHITE} Preparing the build environment${NC}"
echo -e "  ${BLUE}->${WHITE} Creating the 'build' user${NC}"
useradd \
  --create-home --home-dir /build \
  --shell /usr/bin/bash \
  --user-group \
  build
echo -e "  ${BLUE}->${WHITE} Setting up sudo access for 'build' user${NC}"
cat <<- EOF > /etc/sudoers.d/build
build ALL=(ALL) NOPASSWD: /usr/bin/pacman
EOF
echo -e "  ${BLUE}->${WHITE} Creating packages/ directory${NC}"
mkdir -p packages/
echo -e "  ${BLUE}->${WHITE} Changing ownership for build/ and packages/${NC}"
chown build:build -R build/ packages/
echo

# Make sure the system is up-to-date
echo -e "${YELLOW}==>${WHITE} Updating the build environment${NC}"
sudo pacman -Syu --noconfirm --noprogressbar
echo

# Build the package, as required
echo -e "${YELLOW}==>${WHITE} Building the package${NC}"
PKGDEST=$(pwd)/packages
PACKAGER="Jonathan Wright <jon@than.io>"
export PKGDEST PACKAGER
( cd build/ && \
  sudo --user=build -- \
    makepkg --syncdeps --cleanbuild --needed \
      --nosign --noconfirm --noprogressbar 
)
